### ISSUE TITLE
Can we automatically find the ip address the printer is connected to?

### ISSUE THREAD

**Issue by xXAvoraXx** [rubenruvalcabac/epson-epos-sdk-react#3]
Hello, we have a multi-business project, not every business official has to know the ip address of the pos device, so is there a way to find these ip addresses automatically?

**Comment by rubenruvalcabac** [comment]
Don’t think so, but perhaps can use a refer the printer by name using dns

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: xXAvoraXx ***@***.***>
Sent: Sunday, May 7, 2023 7:48:04 AM
To: rubenruvalcabac/epson-epos-sdk-react ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rubenruvalcabac/epson-epos-sdk-react] Can we automatically find the ip address the printer is connected to? (Issue #3)


Hello, we have a multi-business project, not every business official has to know the ip address of the pos device, so is there a way to find these ip addresses automatically?
