### ISSUE TITLE
CORS error when trying to connect to printer

### ISSUE THREAD

**Issue by huydinhle** [rubenruvalcabac/epson-epos-sdk-react#4]
<img width="2022" alt="image" src="https://github.com/rubenruvalcabac/epson-epos-sdk-react/assets/20393709/abf58d89-1604-4be3-a8fb-f032cab5346f">

How do I overcome this problem?

**Comment by betocode** [comment]
How did you solved this @huydinhle ?

**Comment by edvijaka** [comment]
Any luck with this?
